coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

github_checks:
    annotations: false

ignore:
  - "**/_*.py"
  - "setup.py"
  - "**/test_*.py"
  - "manage.py"
  - "_version.py"
  - "**/migrations"
  - "biospecdb/apps/dash"
  - "biospecdb/asgi.py"
  - "biospecdb/wsgi.py"
