version: '3.8'

services:
  db-setup:
    image: biospecdb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biospecdb-db-initializer
    restart: "no"
    volumes:
      - db-data:/app/db
      - spectaldata-files:/app/spectral_data
      - bulk-upload-files:/app/raw_data
      - spectaldata-files:/app/datasets
    environment:
      DJANGO_SETTINGS_MODULE: biospecdb.settings.prd
    secrets:
      - superuser_password
      - django_secret_key
    command: >
      bash -c "set -e
      [ ! -f /app/db/setup_complete.txt ]
      && export SECRET_KEY=$(cat /run/secrets/django_secret_key)
      && python manage.py makemigrations user
      && python manage.py makemigrations uploader
      && python manage.py makemigrations catalog
      && python manage.py migrate
      && python manage.py migrate --database=bsr
      && python manage.py loaddata centers queries
      && python manage.py loaddata --database=bsr centers observables instruments qcannotators biosampletypes spectrameasurementtypes
      && python manage.py update_sql_views
      && DJANGO_SUPERUSER_PASSWORD=$(cat /run/secrets/superuser_password) python manage.py createsuperuser --noinput --username=admin --email=admin@jhu.edu --center=d61f1c2a-9c0a-4309-a031-ab5b8d2106b0
      && touch /app/db/setup_complete.txt || echo done!"

  web:
    depends_on:
      db-setup:
        condition: service_completed_successfully
    image: biospecdb
    deploy:
      mode: global
      restart_policy:
       condition: on-failure
       delay: 5s
       max_attempts: 3
       window: 60s
    expose:
      - 8000
    volumes:
      - db-data:/app/db
      - spectaldata-files:/app/spectral_data
      - bulk-upload-files:/app/raw_data
      - dataset-catalog-files:/app/datasets
      - static_files:/app/static
    environment:
      DJANGO_SETTINGS_MODULE: biospecdb.settings.prd
    secrets:
      - django_secret_key
    command: >
      bash -c "mkdir -p log
      && mkdir -p run
      && SECRET_KEY=$(cat /run/secrets/django_secret_key) python manage.py collectstatic --clear --noinput
      && SECRET_KEY=$(cat /run/secrets/django_secret_key) gunicorn -c config/gunicorn/prd.py"

  nginx:
    build: ./nginx
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    container_name: biospecdb-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_files:/static
      - spectaldata-files:/spectral_data
      - bulk-upload-files:/raw_data
      - dataset-catalog-files:/datasets
    depends_on:
      - web

secrets:
  superuser_password:
    environment: DJANGO_SUPERUSER_PASSWORD
  django_secret_key:
    environment: SECRET_KEY

volumes:
  db-data:
  spectaldata-files:
  bulk-upload-files:
  dataset-catalog-files:
  static_files:
